// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmf3TiU9QsR2FgCC2b8qyQvtF7WYb7h4',
    appId: '1:514278395928:web:57337066619f69718d336d',
    messagingSenderId: '514278395928',
    projectId: 'mad-final2',
    authDomain: 'mad-final2.firebaseapp.com',
    storageBucket: 'mad-final2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUPonzlrn2GDJIM4PkUxy72AMGYI-h4s',
    appId: '1:514278395928:android:1657ad4d275462518d336d',
    messagingSenderId: '514278395928',
    projectId: 'mad-final2',
    storageBucket: 'mad-final2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBScP2KCymQ-vSQaYlyOJIOSdUhlTcB_SA',
    appId: '1:514278395928:ios:04ddce662175e7f38d336d',
    messagingSenderId: '514278395928',
    projectId: 'mad-final2',
    storageBucket: 'mad-final2.appspot.com',
    iosClientId: '514278395928-9i3o7358m23uv0nhphdmqu0icn1b1c23.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBScP2KCymQ-vSQaYlyOJIOSdUhlTcB_SA',
    appId: '1:514278395928:ios:04ddce662175e7f38d336d',
    messagingSenderId: '514278395928',
    projectId: 'mad-final2',
    storageBucket: 'mad-final2.appspot.com',
    iosClientId: '514278395928-9i3o7358m23uv0nhphdmqu0icn1b1c23.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );
}
